
---Olá, deixo aqui o acesso a esse BD completamente populado.
---loguin:rm95546
---Senha:170599









--olá por gentileza seguir todos os passos que estao sendo explicados nos comentarios para assim conseguir rodar o populamento das tabelas e seus devidos vinculos.
--aqui está a logica seguida para o começo da população de toda a tabela: 
--T_IBM_EMPRESA->,T_IBM_END_EMPRESA->,T_IBM_COLABORADOR_EMPRESA-.>,T_IBM_VAGA->,T_IBM_SKILLS->,T_IBM_FEEDbACK->,T_IBM_CANDIDATO->T_IBM_END_CANDIDATO->,T_IBM_SCORE-->,T_IBM_FORMACAO_ACADEMICA-->,T_IBM_CURRICULO-->,T_IBM_PROCESSO_SELETIVO;



--------------SCRIPT DML DE CONSULTA NA TABELA ----------
select * from T_IBM_EMPRESA; 
select * from T_IBM_END_EMPRESA;
SELECT * FROM T_IBM_COLABORADOR_EMPRESA;
SELECT * FROM T_IBM_VAGA;
SELECT * FROM T_IBM_SKILLS;
select * from T_IBM_FEEDbACK;
---------------------------
select * from T_IBM_END_CANDIDATO;
select * from  T_IBM_CANDIDATO;
SELECT * FROM T_IBM_SCORE;
select * from T_IBM_FORMACAO_ACADEMICA;
select * from T_IBM_CURRICULO;
SELECT *  FROM T_IBM_PROCESSO_SELETIVO;


 -----------------CRIANDO A EMPRESA;-----inicio, só criar apenas uma com ID 3.
insert INTO T_IBM_EMPRESA(ID_EMPRESA,CNPJ_EMPRESA,RAZAO_SOCIAL,NOME_FANTASIA,ENDERECO)VALUES(3,14523654785,'serviços e produção','IBM','BRASIL');
 
 ---------------INSERT PARA COLOCAR O END DA EMPRESA, mantendo a relação com a empresa com o ID 3;
INSERT INTO T_IBM_END_EMPRESA(ID_ENDERECO_IBM,ID_EMPRESA,NM_LOGRADOURO,LOGRADOURO,BAIRRO,CEP,UF,PONTO_REFERENCIA)VALUES(1,3,'AV','AV.RICHARDS','FARIA LIMA',78541236,'SP','BRASIL');



--colocar 20 colaboradores.
 INSERT INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR)VALUES(1,3,'frabricio','frabricio@ibm.com.br',1231543,'Coordenador',49382731234,'Pleno');
---MANTEM O ID DA EMPRESA EM 3 E CONTINUA SÓ CRIANDO O COLABORADOR MUDANDO O SEU ID_PK variados.;


--funcionou!inserindo um feedback manual com suas devidas relaçoes com o colaborador--------------- o feedback  varia com o numero de candidatos a vaga
insert INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(1,1,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'));


----insert para adicionar as devidas skills de cada candidato com seus ID variados para ambos .
INSERT INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(1,'Desenvolvedor java','java','expert');
---foi necessario inserir manualmente a loinha de cada tabela, para fazer as suas devidas relaçoes, deixando claro que agora a populaçao delas segue no insert ALL abaixo.


---- foi necessario criar a tab skilss para assim criar o processo de vagas, pois a mesma dependia da FK  da outra tabela para existir, devido ao vinculo, mantendo tambem o ID fixo da empresa.
INSERT INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(1,'JAVA',3,1,1,'SUPERIOR COMPLETO');



---abaixo esta o insert de preenchimento de todas as tabelas do vinculo de candidatos, seguinto a logica apresentada a cima.



 ------------------------alteração com primary e forenkey adicionada, por favor rodar somente esse scrip um select all por vez.
INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(1,'thais',49397316850,527371269,0,'solteirA',99731005,'thais@hotmail.com',to_DATE('17/05/1999','dd/mm/yyyy'),'F','I','I',1234)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(1,1,'Rua','SP','AP',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'Rua Juçara',301,04547088,'São paulo')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(1,1,100,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(1,'superior completo','FIAP',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(1,1,1,1,'APRESENTAÇÃO')
SELECT * FROM DUAL; 
  



INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(2,'Andresa',49397316240,507371269,0,'SOLTEIRA',99731005,'andresa@hotmail.com',to_DATE('02/10/2000','dd/mm/yyyy'),'F','A','A',4567)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(2,2,'Rua','SP','casa',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/2000','dd/mm/yyyy'),'Rua nova cidade',412,04547071,'São paulo')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(2,2,80,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(2,'superior completo','FAM',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(2,'Desenvolvedor c#','c#','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(2,2,2,2,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(3,'Rafael',12456793547,124578956,0,'SOLTEIRO',99731085,'rafael@hotmail.com',to_DATE('24/10/1999','dd/mm/yyyy'),'M','A','A',89101)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(3,3,'Rua','SP','casa fundo',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/2000','dd/mm/yyyy'),'Rua esmeralda',500,12347071,'São paulo')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(3,3,85,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(3,'superior completo','Estacio',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(3,'Desenvolvedor c#','c#','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(3,3,3,3,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(4,'vinicius',12456793447,124578776,0,'SOLTEIRO',99731085,'vini@hotmail.com',to_DATE('17/10/1999','dd/mm/yyyy'),'M','A','A',89113)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(4,4,'av','SC','casa',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/2000','dd/mm/yyyy'),'Av.magalhoes',5000,65485258,'São Caetano')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(4,4,70,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(4,'superior completo','UNIP',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(4,'Desenvolvedor c#','c#','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(4,4,4,4,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(5,'Fernanda',49397845600,114547854,0,'SOLTEIRA',99731085,'fernanda@hotmail.com',to_DATE('24/10/1999','dd/mm/yyyy'),'F','A','A',45871)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(5,5,'AV','SP','AP',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/2000','dd/mm/yyyy'),'Fradique coutinho',100,10047071,'São paulo')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(5,5,95,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(5,'superior completo','eq',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(5,'Desenvolvedor c#','c#','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(5,5,5,5,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(6,'Ana',48175065800,527371478,0,'SOLTEIRA',99731085,'ana@hotmail.com',to_DATE('24/10/1999','dd/mm/yyyy'),'F','A','A',98753)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(6,6,'Condominio','St','AP',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/2000','dd/mm/yyyy'),'Neque. st',2293,04542293,'Pernambuco')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(6,6,66,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(6,'superior completo','UNINOVE',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(6,'Analista Junior Angular','Angular','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(6,6,6,6,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(7,'Julia',00003381170,785244752,0,'SOLTEIRA',99731085,'julia@hotmail.com',to_DATE('24/10/1999','dd/mm/yyyy'),'F','A','A',5678)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(7,7,'Rua','MG','AP',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/2000','dd/mm/yyyy'),'Rua Sevilha',3222,09870071,'Minas Gerais')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(7,7,90,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(7,'superior completo','FAE',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(7,'Desenvolvedor c#','c#','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(7,7,7,7,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(8,'TannerPennington',00031656129,124570965,0,'SOLTEIRA',2103766440,'namligula@gmail.com',to_DATE('24/05/1985','dd/mm/yyyy'),'F','A','A',6500)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(8,8,'Rua','BA','casa',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/2000','dd/mm/yyyy'),'Sobradinho',788,73031601,'brasilia')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(8,8,78,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(8,'superior completo','Anhembi',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(8,'Desenvolvedor c#','c#','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(8,8,8,8,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(9,'pedro',00003381180,524547854,0,'SOLTEIRO',99731085,'pedro@hotmail.com',to_DATE('24/10/1999','dd/mm/yyyy'),'M','A','A',1234)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(9,9,'AV','BH','AP',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/2000','dd/mm/yyyy'),'AFONSO PENA',10,30130003,'BELO HORIZONTE')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(9,9,80,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(9,'superior completo','Unisa',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(9,'Desenvolvedor React','front#','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(9,9,9,9,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(10,'henrique',23003381170,344547854,0,'SOLTEIRO',87731085,'henriq@hotmail.com',to_DATE('28/10/1986','dd/mm/yyyy'),'M','I','I',81399785)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(10,10,'Rua','GO','casa',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/2000','dd/mm/yyyy'),'QUINZE DE NOVEMBRO',1001,74810260,'Goiania')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(10,10,70,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(10,'superior completo','unisantacruz',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(10,'Free lancer c','c','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(10,10,10,10,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(11,'RODRIGO',13003381170,344847854,0,'SOLTEIRO',97731085,'rodrigo@hotmail.com',to_DATE('28/10/1999','dd/mm/yyyy'),'M','I','I',3551482)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(11,11,'AV','RJ','AP',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/2000','dd/mm/yyyy'),'Ttijuca',1000,55547071,'Rio de Janeiro')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(11,11,70,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(11,'superior completo','UFPR',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(11,'Desenvolvedor cobol','cobol','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(11,11,11,11,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(12,'Francimeire',00003381370,785294752,0,'SOLTEIRA',99031085,'Francimeire@hotmail.com',to_DATE('24/10/1970','dd/mm/yyyy'),'F','A','A',8756858)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(12,12,'AV','RJ','AP',to_DATE('05/05/2000','dd/mm/yyyy'),to_DATE('28/10/2500','dd/mm/yyyy'),'copacabana',82,04544321,'Rio de Janeiro')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(12,12,51,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(12,'superior completo','FAM',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(12,' c#','c#','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(12,12,12,12,'APRESENTAÇÃO')
SELECT * FROM DUAL;


INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(13,'MARCIA',00045286620,045286620,0,'SOLTEIRA',999954490,'marcia@hotmail.com',to_DATE('24/10/1970','dd/mm/yyyy'),'F','A','A',0004352793)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(13,13,'CASA','LD','AP',to_DATE('05/05/2000','dd/mm/yyyy'),to_DATE('28/10/2500','dd/mm/yyyy'),'ALVIN BAUER',77,74000000,'LONDRINA')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(13,13,51,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(13,'superior completo','FMU',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(13,'Desenvolvedor c#','c#','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(13,13,13,13,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(14,'ANITA',00046222278,046222278,0,'SOLTEIRA',995381516,'anita@hotmail.com',to_DATE('24/10/1970','dd/mm/yyyy'),'F','I','A',00045286620)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(14,14,'RUA','RJ','AP',to_DATE('05/05/2000','dd/mm/yyyy'),to_DATE('28/10/2500','dd/mm/yyyy'),'PARANAGUÁ',1,88330640,'Rio de Janeiro')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(14,14,51,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(14,'superior completo','UNIP',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(14,'Desenvolvedor c#','c#','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(14,14,14,14,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(15,'Marcos',00122170695,122170695,0,'SOLTEIRO',81378125,'Marcos@hotmail.com',to_DATE('24/10/1970','dd/mm/yyyy'),'M','I','I',00078383102)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(15,15,'AV','RJ','AP',to_DATE('05/05/2000','dd/mm/yyyy'),to_DATE('28/10/2500','dd/mm/yyyy'),'copacabana',50,74810220,'Rio de Janeiro')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(15,15,51,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(15,'superior completo','Mackenzie',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(15,'Analista BD','SQL server','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(15,15,15,15,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(16,'Willian',00121985016,121985016,0,'SOLTEIRO',999117770,'Willian@hotmail.com',to_DATE('24/10/1970','dd/mm/yyyy'),'M','A','I',00080695655)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(16,16,'rua','SP','AP',to_DATE('05/05/2000','dd/mm/yyyy'),to_DATE('28/10/2500','dd/mm/yyyy'),'copacabana',05,74810230,'sa paulo')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(16,16,51,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(16,'superior completo','Mackenzie',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(16,'Analista BD','Oracle','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(16,16,16,16,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(17,'Murilo',00116987804,16987804,0,'SOLTEIRO',999942503,'Murilo@hotmail.com',to_DATE('24/10/1970','dd/mm/yyyy'),'M','I','A',00084576707)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(17,17,'AV','SP','AP',to_DATE('05/05/2000','dd/mm/yyyy'),to_DATE('28/10/2500','dd/mm/yyyy'),'copacabana',87,69057021,'sao paulo')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(17,17,51,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(17,'superior completo','Mackenzie',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(17,'Desenvolvedor Front','JS','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(17,17,17,17,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(18,'Marta',00113799950,113799950,0,'SOLTEIRA',996641911,'Marta@hotmail.com',to_DATE('24/10/1970','dd/mm/yyyy'),'F','A','A',00086700804)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(18,18,'AV','SP','AP',to_DATE('05/05/2000','dd/mm/yyyy'),to_DATE('28/10/2500','dd/mm/yyyy'),'copacabana',00,69060103,'sao paulo')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(18,18,51,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(18,'ciencia da computação','Unesp',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'Concluido')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(18,'Suporte Analitico','informativa','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(18,18,18,18,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(19,'Rebeca',00108046176,108046176,0,'SOLTEIRA',34246211,'Rebeca@hotmail.com',to_DATE('24/10/1970','dd/mm/yyyy'),'F','I','A',00102421129)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(19,19,'CONDOMINIO','SP','AP',to_DATE('05/05/2000','dd/mm/yyyy'),to_DATE('28/10/2500','dd/mm/yyyy'),'copacabana',21,89010310,'sao paulo')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(19,19,51,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(19,'concursando','FMU',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'ADS')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(19,'Desenvolvedor python','python','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(19,19,19,19,'APRESENTAÇÃO')
SELECT * FROM DUAL;

INSERT ALL 
    INTO T_IBM_CANDIDATO(ID_CANDIDATO,NOME_CANDIDATO,CPF_CANDIDATO,RG_CANDIDATO,RNE_CANDIDATO,ESTADO_CIVIL,TEL_CANDIDATO,EMAIL_CANDIDATO,DATA_NASCIMENTO,GENERO_CANDIDATO,ST_TELEFONE_CANDIDATO,ST_EMAIL_CANDIDATO,SENHA) VALUES(20,'Barbara',00107576198,107576198,0,'SOLTEIRA',984108618,'Barbara@hotmail.com',to_DATE('24/10/1970','dd/mm/yyyy'),'F','A','I',00105339156)
    INTO T_IBM_END_CANDIDATO(ID_ENDERECO,ID_CANDIDATO,LOGRADOURO,UF,PONTO_REFERENCIA,DT_INICIO,DT_FIM,NM_LOGRADOURO,BAIRRO,CEP,CIDADE)VALUES(20,20,'CASA','SP','AP',to_DATE('05/05/2000','dd/mm/yyyy'),to_DATE('28/10/2500','dd/mm/yyyy'),'MARECHAL CASTELO BRANCO',21,74835145,'Sao paulo')
    INTO T_IBM_SCORE(ID_SCORE,ID_CANDIDATO,SCORE,DATA_SCORE)VALUES(20,20,51,to_DATE('05/05/2000','dd/mm/yyyy'))
    INTO T_IBM_FORMACAO_ACADEMICA(ID_FORMACAO,NIVEL_FORMACAO,INSTITUICAO,DATA_INICIO,DATA_FIM,STATUS)values(20,'Completo','USP',to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),'Terminado')
    INTO T_IBM_SKILLS (ID_SKILL,NOME_SKILL,TIPO_SKILL,NIVEL_SKILL)values(20,'Desenvolvedor java','java','expert')
    INTO T_IBM_CURRICULO(ID_CURRICULO,ID_CANDIDATO,ID_FORMACAO,ID_SKILL,APRESENTACAO_PESSOAL)VALUES(20,20,20,20,'APRESENTAÇÃO')
SELECT * FROM DUAL;
------------------------------------------------------------------------------------------------------------------------------------------------

----se voce chegou até aqui, esta seguindo os passos corretamente, agora antes de rodar o script de inserir o processo seletivo, pule para a etapa INSERT ALL e rode todos os inserts all primeiro, e depois volte a baixo e  insira o insert ABAIXO(T_IBM_PROCESSO_SELETIVO).

insert INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(1,1,1,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),1);
---ultima tabela a ser populada, devida a suas relaçoes.
-- para o processo seletivo existir foi necessario que a empresa fosse criada antes e todos os seus passos, e depois os candidatos fossem preenchidos sendo a ultima tabela a ser populada.

-------------todos os selects para visualizar as tabelas preenchidas------
select * from T_IBM_EMPRESA; 
select * from T_IBM_END_EMPRESA;
SELECT * FROM T_IBM_COLABORADOR_EMPRESA;
SELECT * FROM T_IBM_VAGA;
SELECT * FROM T_IBM_SKILLS;
SELECT *  FROM T_IBM_PROCESSO_SELETIVO;
select * from T_IBM_FEEDbACK;
select * from T_IBM_END_CANDIDATO;
select * from  T_IBM_CANDIDATO;
SELECT * FROM T_IBM_SCORE;
select * from T_IBM_FORMACAO_ACADEMICA;
select * from T_IBM_CURRICULO;


----------------------------aqui irei fazer os devido populamentos da tabela---------------

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(2,3,'Andre','Andre@ibm.com.br',1231543,'Recursos Humano',55382731234,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(2,2,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(2,'PYTHON',3,2,2,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(2,2,2,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),2)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(3,3,'Andreia','Andreia@ibm.com.br',00277997194,'Recursos Humano',99382731234,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(3,3,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(3,'PYTHON',3,3,3,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(3,3,3,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),3)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(4,3,'Renata','renata@ibm.com.br',00275826040,'Recursos Humano',00083924043,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(4,4,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(4,'C#',3,4,4,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(4,4,4,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),4)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(5,3,'ingrid','ingrid@ibm.com.br',00268449660,'Recursos Humano',00084576707,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(5,5,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(5,'C#',3,5,5,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(5,5,5,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),5)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(6,3,'jonata','jonata@ibm.com.br',00267834608,'Recursos Humano',00084916826,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(6,6,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(6,'REACT',3,6,6,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(6,6,6,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),6)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(7,3,'Pedro','pedro@ibm.com.br',1231543,'Recursos Humano',00086700804        ,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(7,7,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(7,'ANALISTA BD',3,7,7,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(7,7,7,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),7)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(8,3,'gisele','gisele@ibm.com.br',00265201179,'Recursos Humano',00105339156,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(8,8,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(8,'ANALISTA DADOS ',3,8,8,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(8,8,8,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),8)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(9,3,'daniela','daniela@ibm.com.br',00251112640,'Recursos Humano',00113797907,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(9,9,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(9,'RH',3,9,9,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(9,9,9,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),9)
SELECT * FROM DUAL; 
INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(10,3,'Andre','Andre@ibm.com.br',00249717158,'Recursos Humano',00123357110,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(10,10,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(10,'MARKETIN',3,10,10,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(10,10,10,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),10)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(11,3,'Andre','Andre@ibm.com.br',00245866337,'Recursos Humano',00130074675,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(11,11,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(11,'PYTHON',3,11,11,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(11,11,11,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),11)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(12,3,'Andre','Andre@ibm.com.br',00225110164,'Recursos Humano',00132067102,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(12,12,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(12,'CIENCIA DA COMPUTAÇÃO',3,12,12,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(12,12,12,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),12)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(13,3,'Andre','Andre@ibm.com.br',00221450106,'Recursos Humano',00141359900,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(13,13,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(13,'LINGUAGEM C',3,13,13,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(13,13,13,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),13)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(14,3,'Andre','Andre@ibm.com.br',00221879285,'Recursos Humano',00149940203,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(14,14,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(14,'PHP',3,14,14,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(14,14,14,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),14)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(15,3,'Andre','Andre@ibm.com.br',00222583100,'Recursos Humano',00155977253,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(15,15,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(15,'HTML',3,15,15,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(15,15,15,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),15)
SELECT * FROM DUAL;

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(16,3,'Andre','Andre@ibm.com.br',00188522549,'Recursos Humano',00157912620,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(16,16,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(16,'CSS',3,16,16,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(16,16,16,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),16)
SELECT * FROM DUAL;



 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(18,3,'Andre','Andre@ibm.com.br',00188522549,'Recursos Humano',00156629690,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(18,18,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(18,'FULL STACK',3,18,18,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(18,18,18,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),18)
SELECT * FROM DUAL; 

INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(19,3,'Andre','Andre@ibm.com.br',00181484331,'Recursos Humano',00169742636,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(19,19,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(19,'COMERCIAL VENDAS',3,19,19,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(19,19,19,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),19)
SELECT * FROM DUAL; 


INSERT ALL
        INTO T_IBM_COLABORADOR_EMPRESA(ID_COLABORADOR,ID_EMPRESA,NOME_COLABORADOR,EMAIL_COLABORADOR,SENHA,CARGO_COLABORADOR,CPF_COLABORADOR,NV_COLABORADOR) VALUES(20,3,'Andre','Andre@ibm.com.br',00186053037,'Recursos Humano',00187102120,'Pleno')
        INTO T_IBM_FEEDBACK(ID_FEEDBACK,ID_COLABORADOR,TIPO_FEEDBACK,DESC_FEEDBACK,DATA_FEEDBACK)VALUES(20,20,'Conversasao','apontamento de melhoria sobre a vaga',to_DATE('05/05/2005','dd/mm/yyyy'))
        INTO T_IBM_VAGA(ID_VAGA,DESCRICAO_VAGA,ID_EMPRESA,ID_SKILL,ID_FEEDBACK,REQUISITO_NIVEL_ACADEMICO)VALUES(20,'Java',3,20,20,'SUPERIOR COMPLETO')
        INTO T_IBM_PROCESSO_SELETIVO(ID_PROCESSO_SELETIVO,ID_VAGA,ID_CURRICULO,DATA_INICIO,DATA_FIM,ID_FEEDBACK)VALUES(20,20,20,to_DATE('05/05/2005','dd/mm/yyyy'),to_DATE('28/10/1999','dd/mm/yyyy'),20)
SELECT * FROM DUAL; 

 
 